#!/bin/sh

# Source system configurations.
if [ -d /etc/X11/xinit/xinitrc.d ]; then
  for f in /etc/X11/xinit/xinitrc.d/?*.sh; do
    [ -x "$f" ] && . "$f"
  done
  unset f
fi

# Source X resources.
xresources="${0%/*}/xresources"
if [ -f "${xresources}" ]; then
  xrdb -merge "${xresources}"
fi

exec bspwm
