#!/bin/sh

# Source X resources.
xresources="${0%/*}/xresources"
if [ -f "${xresources}" ]; then
  xrdb -merge "${xresources}"
fi

# Input Method
export GTK_IM_MODULE=fcitx
export QT_IM_MODULE=fcitx
export SDL_IM_MODULE=fcitx
export XMODIFIERS=@im=fcitx

exec bspwm
