set-option global autocomplete prompt

add-highlighter global/show-whitespaces show-whitespaces -spc ' '
colorscheme mico

hook global InsertChar '\t' %{ try %{
  execute-keys -draft "h<a-h><a-k>\A\h+\z<ret><a-;>;%opt{indentwidth}@"
}}

hook global InsertDelete ' ' %{ try %{
  execute-keys -draft 'h<a-h><a-k>\A\h+\z<ret>i<space><esc><lt>'
}}

hook global BufWritePre .* %{ try %{
  execute-keys -draft '%s\h+$<ret>d'
}}
