#!/bin/sh

# Configuration

bspc monitor -d I II III IV V VI VII VIII IX X

# Colors
bspc config active_border_color '#a626a4'
bspc config focused_border_color '#0184bc'
bspc config normal_border_color '#383a42'

# Dimensions
bspc config border_width 4
bspc config split_ratio 0.5

bspc config top_padding 8
bspc config right_padding 8
bspc config bottom_padding 8
bspc config left_padding 8

bspc config window_gap 8

bspc config borderless_monocle true
bspc config gapless_monocle true

# Rules
bspc rule -a KeePassXC state=floating center=on

# Oneshot
xsetroot -cursor_name left_ptr
hsetroot -fill "${HOME}/media/images/wallpaper/bg.jpg"

# Services
pgrep --exact sxhkd >/dev/null || sxhkd &
pgrep --exact fcitx5 >/dev/null || fcitx5 &
