#!/usr/bin/env zsh

dir=${0%/*}

exec alacritty \
  --class 'Lunch' \
  --option window.dimensions.columns=40 \
  --option window.dimensions.lines=8 \
  --option window.padding.x=30 \
  --option window.padding.y=30 \
  --command "${dir}/lunch"
